# Generated by Django 3.2 on 2022-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220917_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, default=False, upload_to='faculty_images/'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='time',
            field=models.DateField(blank=True),
        ),
    ]
