# Generated by Django 3.2 on 2022-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_admin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
