# Generated by Django 3.2 on 2022-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_admin_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('contactno', models.IntegerField(unique=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
